version: '2'
services:
  web:
    build: .
    command: npm start
    volumes: 
      - .:/dist/
      - /dist/node_modules
    ports:
      - "3000:1701"
    depends_on:
      - postgres
    environment:
      DB_URL: postgres://guamkgyi:p6JxRxTM4R9E0k_FR_zzK7Y-NPJzm00y@pellefant.db.elephantsql.com:5432/guamkgyi
      NODE_ENV: production
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: lyfenapp
      POSTGRES_DB: lyfen