version: '2'
services:
  api:
    build: .
    command: npm start
    volumes: 
      - .:/dist/
    ports:
      - "1701:1701"
    depends_on:
      - postgres
    environment:
      DB_URL: postgres://guamkgyi:p6JxRxTM4R9E0k_FR_zzK7Y-NPJzm00y@pellefant.db.elephantsql.com:5432/guamkgyi
      DATABASE_URL: postgres://postgres@postgres/postgres
      NODE_ENV: dev
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
  webapp:
    image: lyfen-webapp
    command: npm start
    ports:
      - "80:3000"